### ISSUE TITLE
error on attempting to update all plugins

### ISSUE THREAD

**Issue by werken23** [Lenni0451/SpigotPluginManager#13]
[14:19:16 INFO]: werken23 issued server command: /pm update *
[14:19:16 WARN]: java.lang.IndexOutOfBoundsException: Index: 21, Size: 20
[14:19:16 WARN]: at PluginManager-2.7.jar//net.lenni0451.spm.utils.PluginUtils.getPluginsByLoadOrder(PluginUtils.java:385)
[14:19:16 WARN]: at PluginManager-2.7.jar//net.lenni0451.spm.commands.subs.Update_Sub.execute(Update_Sub.java:27)
[14:19:16 WARN]: at PluginManager-2.7.jar//net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
[14:19:16 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

**Comment by Lenni0451** [comment]
I still don't really know how this occurrs but it should be fixed now

**Comment by Lenni0451** [comment]
Would be nice if you could test it now and reply if there should be any other problems

**Comment by werken23** [comment]
I'm not getting any command feedback when executing the command on the new build, plugin files seem unchanged but that might be because there are no new versions available.

**Comment by Jaynator495** [comment]
I'm also having this same problem - while I'm no longer getting the exception, I'm also not getting any output

**Comment by Lenni0451** [comment]
I just found out that I used the same message key two times. However this should still print a message. Is there no exception or anything in the console?

**Comment by Jaynator495** [comment]
No, the index exception is gone, instead replaced by nothing. No other errors, no messages, and server just proceeds as usual as far as I can tell

**Comment by werken23** [comment]
same

**Comment by Lenni0451** [comment]
If anyone of you is still interested in this Issue after 5 Months of nothing please leave a comment so I can get in touch with you because I still don't know why nothing is happening for you and I need more Information
