### ISSUE TITLE
PluginManager fails to recognize paper-plugin.yml

### ISSUE THREAD

**Issue by SlimeDog** [Lenni0451/SpigotPluginManager#24]
In order to test the new Paper `paper-plugin.yml` file, I manually added the following to my `PluginVersions` resource
```
$ cat paper-plugin.yml 
name: PluginVersions
version: 1.1.0
api-version: 1.19
main: com.straight8.rambeau.bukkit.PluginVersionsBukkit
description: List installed plugins and versions alphabetically
authors: [drives_a_ford, GabrielHD150, SlimeDog]
commands:
  pluginversions:
    description: Commands for PluginVersions
    usage: <command> list | <command> reload
    aliases: [pv]
  pluginversions list:
    description: List loaded plugins and versions
    usage: <command> [page]
  pluginversions reload:
    description: Reload configuration file
    usage: <command>
permissions:
  pluginversions.*:
    description: Allows access to all PluginVersions commands
    children:
      pluginversions.list: true
      pluginversions.reload: true
  pluginversions.list:
    description: Allows you to retrieve PluginVersions listing
    default: op
  pluginversions.reload:
    description: Allows you to reload PluginVersions configuration
    default: op

$ zip -r plugins/PluginVersions-1.1.0.jar paper-plugin.yml
  adding: paper-plugin.yml (deflated 62%)

$ unzip -l plugins/PluginVersions-1.1.0.jar 
      208  11-22-2021 08:25   bungee.yml
        0  11-22-2021 08:25   com/
...
      349  11-22-2021 08:25   config.yml
     1085  11-22-2021 08:25   plugin.yml
      267  11-22-2021 08:25   velocity-plugin.json
      934  02-24-2023 11:08   paper-plugin.yml
```

When I restart the server, `PluginVersions` is loaded and enabled.
```
...
[11:13:18] [Server thread/INFO]: [PluginVersions] Loading server plugin PluginVersions
[11:14:17] [Server thread/INFO]: [PluginVersions] Enabling PluginVersions
...
> version
[11:20:14 INFO]: This server is running Paper version git-Paper-420 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 81d7ff6)
You are running the latest version
Previous version: git-Paper-418 (MC: 1.19.3)

> version PluginManager
[11:20:52 INFO]: PluginManager version 2.7.4
[11:20:52 INFO]: Author: Lenni0451

> version PluginVersions
[11:21:45 INFO]: PluginVersions version 1.1.0
[11:21:45 INFO]: List installed plugins and versions alphabetically
[11:21:45 INFO]: Authors: drives_a_ford, GabrielHD150 and SlimeDog
```

If I attempt to use `PluginManager` to unload and re-load the plugin, `load` fails.
```
> pm unload PluginVersions
[11:16:38 INFO]: [PluginVersions] Disabling PluginVersions
[11:16:38 INFO]: PM | The plugin has been unloaded.

> pm load PluginVersions
[11:17:17 WARN]: java.lang.IllegalStateException: Invalid plugin file
[11:17:17 WARN]:        at PluginManager-2.7.4.jar//net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:255)
[11:17:17 WARN]:        at PluginManager-2.7.4.jar//net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55)
[11:17:17 WARN]:        at PluginManager-2.7.4.jar//net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
[11:17:17 WARN]:        at PluginManager-2.7.4.jar//net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110)
[11:17:17 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:17:17 WARN]:        at EssentialsX-2.20.0+43-25ad8ac.jar//com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:737)
[11:17:17 WARN]:        at EssentialsX-2.20.0+43-25ad8ac.jar//com.earth2me.essentials.Essentials.onCommand(Essentials.java:723)
[11:17:17 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:17:17 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[11:17:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912)
[11:17:17 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:875)
[11:17:17 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:501)
[11:17:17 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[11:17:17 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[11:17:17 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[11:17:17 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:17:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[11:17:17 INFO]: PM | Could not load the plugin PluginVersions. (Invalid plugin file)
```

**Comment by Lenni0451** [comment]
Paper plugins themselves are not supported yet. The latest release only fixes loading/unloading of bukkit plugins. I'm not sure if I will add full support for paper plugins in PM at this point of time because I am currently working on a recode (V3) because the old code is bad and I don't like it anymore. I will take a look anyways and see if it is worth adding to the old code...

**Comment by SlimeDog** [comment]
Speaking only for myself, targeting V3 is fine.

**Comment by SlimeDog** [comment]
V3 hasn't been touched in 4 months. Any estimate as to when it will be ready for testing?

**Comment by Lenni0451** [comment]
Tbh I've pretty much lost interest in spigot plugin coding. I'm not sure when or even if there will be any usable state of v3. But I might try picking it up again after this "break" I had for the last 4 months...
