### ISSUE TITLE
Loading plugins asks for dependancies

### ISSUE THREAD

**Issue by ItsVaidas** [Lenni0451/SpigotPluginManager#25]
[17:54:28 INFO]: [ZCBluePrintsCreative] Disabling ZCBluePrintsCreative v1.0
[17:54:28 ERROR]: [ModernPluginLoadingStrategy] Could not load './plugins/ZCBluePrintsCreative.jar' in './plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [AsVaidasAPI]. Please download and install these plugins to run 'ZCBluePrintsCreative'.
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:80) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:249) ~[PluginManager.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:213) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.subs.Reload_Sub.execute(Reload_Sub.java:38) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[PluginManager.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:925) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:888) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:542) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:489) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:54:28 WARN]: java.lang.IllegalStateException: Invalid plugin file
[17:54:28 WARN]:        at PluginManager.jar//net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:255)
[17:54:28 WARN]:        at PluginManager.jar//net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:213)
[17:54:28 WARN]:        at PluginManager.jar//net.lenni0451.spm.commands.subs.Reload_Sub.execute(Reload_Sub.java:38)
[17:54:28 WARN]:        at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
[17:54:28 WARN]:        at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110)
[17:54:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:54:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:54:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:925)
[17:54:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:888)
[17:54:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:542)
[17:54:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:489)
[17:54:28 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[17:54:28 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[17:54:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:54:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:54:28 INFO]: PM | Could not load the plugin ZCBluePrintsCreative. (Invalid plugin file)

Loading a plugin will ask for dependancies to be installed, but those are already installed.

**Comment by Lenni0451** [comment]
You are using a paper version > 404. This is an issue with paper which I am currently not able to fix. The new api is pretty volatile and may change any time so supporting this is currently not really feasible.
See https://github.com/Lenni0451/SpigotPluginManager/issues/22#issuecomment-1445445072
