### ISSUE TITLE
Dependency fail when trying to load plugin jar

### ISSUE THREAD

**Issue by cupang-afk** [Lenni0451/SpigotPluginManager#26]
i want to load this plugin [ActionAnnouncer](https://www.spigotmc.org/resources/announcer-plus-hex-rgb-placeholderapi-json-toast.81005/)
the plugin require [Vault](https://www.spigotmc.org/resources/vault.34315/) as dependency

i got 
```
[11:55:29 ERROR]: [ModernPluginLoadingStrategy] Could not load './plugins/AnnouncerPlus-1.3.4.jar' in './plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Vault]. Please download and install these plugins to run 'AnnouncerPlus'.
	at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:80) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:249) ~[PluginManager.jar:?]
	at net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[PluginManager.jar:?]
	at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[PluginManager.jar:?]
	at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[PluginManager.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:925) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:888) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:542) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:489) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

by using command `pluginmanager list`

i can confirm vault is loaded 
```
[11:59:57 INFO]:  - Vault 1.7.3-b131
[11:59:57 INFO]:  - VentureChat 3.5.0
[11:59:57 INFO]:  - ViaBackwards 4.6.1
[11:59:57 INFO]:  - ViaVersion 4.6.1
and the rest of plugins
```

server version 

```
[12:03:07 INFO]: Current: git-Purpur-1933 (MC: 1.19.3)*
```

**Comment by Lenni0451** [comment]
This is sadly an issue I am unable to fix. Newer versions of Paper and it's forks (like Purpur) made many changes to the way how plugins are loaded. Paper 1.19.3 since build 404 expects all plugins to be loaded at the same time. Currently I don't know any way around this limitation

**Comment by cupang-afk** [comment]
> Paper 1.19.3 since build 404 expects all plugins to be loaded at the same time

so that is the case

i also tried other plugin manager like [PlugWoman](https://www.spigotmc.org/resources/plugwoman.82302/) and it show same behaviour :(

**Comment by patyhank** [comment]
I have modified the plugin to make the feature available temporarily.
[SpigotPluginManager.zip](https://github.com/Lenni0451/SpigotPluginManager/files/11238956/SpigotPluginManager.zip)

*This is the version I took for my own use. This version ignores the depend field so that Paper can read it normally (other depends are loaded as usual when running)

**Comment by Lenni0451** [comment]
> I have modified the plugin to make the feature available temporarily. [SpigotPluginManager.zip](https://github.com/Lenni0451/SpigotPluginManager/files/11238956/SpigotPluginManager.zip)
> 
> *This is the version I took for my own use. This version ignores the depend field so that Paper can read it normally (other depends are loaded as usual when running)

Wow, this is really cool. Would you be able to share the modifications you made or maybe even open a pull request?

**Comment by patyhank** [comment]
> Wow, this is really cool. Would you be able to share the modifications you made or maybe even open a pull request?

https://github.com/patyhank/SpigotPluginManager

I committed the changes in my fork
It will need to use the paper-server, so it must first compile the paper and publish it to the Local Maven Repository
