### ISSUE TITLE
Warn in console

### ISSUE THREAD

**Issue by Floodo** [Lenni0451/SpigotPluginManager#29]
Hello :) I just started server (Paper 1.19) and than this warn message shows up in console.

[17:36:57 INFO]: PM | An unknown error occurred whilst checking for a new PluginManager version!.
[17:36:57 WARN]: java.io.IOException
[17:36:57 WARN]:        at PluginManager (3).jar//net.lenni0451.spm.utils.DownloadUtils.getNewestVersion(DownloadUtils.java:153)
[17:36:57 WARN]:        at PluginManager (3).jar//net.lenni0451.spm.PluginManager.lambda$checkUpdates$2(PluginManager.java:92)
[17:36:57 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:36:57 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:36:57 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:36:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:36:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:36:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Lenni0451** [comment]
Hey, this seems to be an issue on your end. I tried it locally and everything worked without any issues.
